[versions]
agp = "8.11.1"
androidMapsUtils = "3.19.0"
converterGson = "3.0.0"
guava = "33.4.8-android"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
mapsCompose = "6.7.0"
navigationCompose = "2.9.3"
navigationRuntimeKtx = "2.9.3"
accompanistPermissions = "0.37.3"
healthConnect = "1.1.0-rc03"
material = "1.12.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.3"
navigationUiKtx = "2.9.3"
mlVision = "16.1.7"
faceMeshDetection = "16.0.0-beta3"
cameraCore = "1.4.2"
playServicesLocation = "21.3.0"
playServicesMaps = "19.2.0"
playServicesVisionCommon = "19.1.3"
media3Ui = "1.8.0"
media3Exoplayer = "1.8.0"
pagingComposeAndroid = "3.3.6"
coil-compose = "2.7.0"
runtime = "1.9.2"
# Utilities
socketIo = "0.6.0"
timber = "5.0.1"
litert = "2.0.2"
cookiebar2 = "1.1.5"
#Google Credential Manager
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"

tensorflowLite = "2.17.0"
tfLiteVision = "0.4.4"
tensorflowLiteSupport = "0.5.0"
tensorflowLiteMetadata = "0.5.0"

[libraries]
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-accompanist = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
health-connect = { group = "androidx.health.connect", name = "connect-client", version.ref = "healthConnect" }
litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mlkit-facedetection = { group = "com.google.mlkit", name = "face-detection", version.ref = "mlVision" }
mlkit-face-mesh-detection = { group = "com.google.mlkit", name = "face-mesh-detection", version.ref = "faceMeshDetection" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCore" }
camera-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "cameraCore" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraCore" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraCore" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "cameraCore" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraCore" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-vision-common = { group = "com.google.android.gms", name = "play-services-vision-common", version.ref = "playServicesVisionCommon" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-paging-compose-android = { group = "androidx.paging", name = "paging-compose-android", version.ref = "pagingComposeAndroid" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
# Utilities
socket-io = { module = "dev.icerock.moko:socket-io", version.ref = "socketIo" }
tf-lite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
tf-task-vision = { group = "org.tensorflow", name = "tensorflow-lite-task-vision", version.ref = "tfLiteVision" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
tensorflow-lite-metadata = { group = "org.tensorflow", name = "tensorflow-lite-metadata", version.ref = "tensorflowLiteMetadata" }
tensorflow-lite-gpu = { group = "org.tensorflow", name = "tensorflow-lite-gpu", version.ref = "tensorflowLite" }
cookiebar2 = { module = "org.aviran.cookiebar2:cookiebar2", version.ref = "cookiebar2" }
#Google Credential Manager
google-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
google-credentials-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
google-credentials-id = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

